---
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: backstage-dev-bucket
  namespace: backstage
  labels:
    backstage.io/kubernetes-id: backstage
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: backstage-dev-bucket
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: gcp-provider
  deletionPolicy: Delete