apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-secrets
  namespace: postiz
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: postiz-secrets
  data:
    - secretKey: JWT_SECRET
      remoteRef: {key: postiz, property: jwt-secret}
    - secretKey: DATABASE_URL
      remoteRef: {key: postiz, property: database-url}
    - secretKey: REDIS_URL
      remoteRef: {key: postiz, property: redis-url}
