{{- if not .Values.parent }}
{{- $globalConfig := .Values }}
{{- $path := printf "**/%s.yaml" .Values.env }}
{{- range $key, $value := .Files.Glob $path }}
{{- $appConfig := $.Files.Get $key | fromYaml }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appConfig.chart.name }}-{{ $globalConfig.env }}
  namespace: {{ $globalConfig.source.namespace }}
  labels:
    env: {{ $globalConfig.env }}
    app: {{ $appConfig.chart.name }}
{{ required "labels field is required"  $appConfig.labels | toYaml | indent 4 }}
spec:
  source:
{{- if $appConfig.chart.path }}
    path: {{ $appConfig.chart.path }}
    repoURL: {{ $appConfig.chart.url }}
    directory:
      recurse: {{ $appConfig.chart.recurseDirectory | default "false" }}
{{- else }}
    chart: {{ $appConfig.chart.name }}
    repoURL: {{ $appConfig.chart.url }}
    helm:
      values: |
{{- if $appConfig.values }}
{{ $appConfig.values | indent 8 }}
{{- end }}
{{- end }}
    targetRevision: {{ $appConfig.chart.targetRevision }}

  destination:
    namespace: {{ $appConfig.chart.namespace }}
    server: {{ $globalConfig.destination.server }}
  project: {{ $globalConfig.project }}
  syncPolicy:
    automated:
      selfHeal: {{ $appConfig.syncPolicy.selfHeal | default "false" }}
      prune: {{ $appConfig.syncPolicy.prune | default "false" }}
    syncOptions:
    - CreateNamespace=true
{{- end }}
{{- end }}