apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ciso-assistant-db
  namespace: ciso-assistant
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: ciso-assistant-db}
  data:
    - secretKey: postgres-password
      remoteRef: {key: ciso-assistant, property: db-password}
    - secretKey: password
      remoteRef: {key: ciso-assistant, property: db-password}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ciso-assistant-django
  namespace: ciso-assistant
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: ciso-assistant-django}
  data:
    - secretKey: django-secret-key
      remoteRef: {key: ciso-assistant, property: django-secret-key}
