---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitbucket-pat-credentials
  namespace: ci
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: git-bitbucket-pat-access
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "usernamePassword"
        annotations:
          "jenkins.io/credentials-description": "bitbucket user access"
      data:
        username: >- 
          {{ printf "{{ .username | toString }}" }}
        password: >-
          {{ printf "{{ .password | toString }}" }}

  data:
    - secretKey: username
      remoteRef:
        key: bitbucket-credentials
        property: bitbucket-ssh-access-username
    - secretKey: password
      remoteRef:
        key: bitbucket-credentials
        property: bitbucket-personal-access-token
