---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat-credentials
  namespace: ci
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: github-pat-credentials
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "usernamePassword"
        annotations:
          "jenkins.io/credentials-description": "github user access"
      data:
        username: >- 
          {{ printf "{{ .username | toString }}" }}
        password: >-
          {{ printf "{{ .password | toString }}" }}

  data:
    - secretKey: username
      remoteRef:
        key: github-credentials
        property: github-ssh-access-username
    - secretKey: password
      remoteRef:
        key: github-credentials
        property: github-personal-access-token
