apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "jenkins-ingress"
  namespace: "ci"
  labels:
    app: jenkins-ingress
spec:
  rules:
    - host: build.polarpoint.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: "jenkins-non-prod"
              servicePort: 8080