apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "jenkins-np-ingress"
  namespace: "ci"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: build-np.services.polcloud.org
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:eu-west-2:700677256593:regional/webacl/jenkins-np-web-acl/df61226d-5fd8-4a96-a852-6fb4e47f409f
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=hrz-all-s3-alb-logs,access_logs.s3.prefix=jenkins-np
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 'subnet-098b04b5a0fd5aad2, subnet-0e526cdc461ae3e55, subnet-0809835826236e46c'
    alb.ingress.kubernetes.io/security-groups: sg-015433d1cc0f0ae65
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:700677256593:certificate/d72c24ed-40f2-428e-9115-559b743e2c1c
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:eu-west-2:700677256593:userpool/eu-west-2_RIGVTbbm0", "UserPoolClientId":"qoj3b4aba3tgardohh2sqetqm", "UserPoolDomain":"dev-ops-tool-jenkins-np"}'
    alb.ingress.kubernetes.io/tags: Name=Jenkins-np-ALB,NAME=Jenkins-np-ALB,owner=cloudops,cost-centre=114773,environment=shared-services,data-compliance=none
  labels:
    app: jenkins-np-ingress
spec:
  rules:
    - host: build-np.services.polcloud.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: "jenkins-non-prod"
              servicePort: 8080