apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: ci
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
    
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: jenkins-non-prod
            port:
              number: 8080
    host: build.polarpoint.io
  tls:
  - hosts:
    - build.polarpoint.io
    secretName: nginx-ssl-jenkins
