apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  annotations:
  name: backstage-github-authentication
  namespace: platform
spec:
  refreshInterval: 24h0m0s
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: github-client-id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: github-client-secret
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: github-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets-store
  target:
    creationPolicy: Owner
    name: backstage-github-authentication
