apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  annotations:
  name: sonarqube-database-authentication
  namespace: platform
spec:
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: sonarqube-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: sonarqube-postgres-password
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: sonarqube-postgres-port
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets-store
  target:
    creationPolicy: Owner
    name: sonarqube-database-authentication
