---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: capmaas-manager-bootstrap-credentials
  namespace: capmaas-system
spec:
  refreshInterval: 24h0m0s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets-store               # name of the SecretStore (or kind specified)
  target:
    name: capmaas-manager-bootstrap-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cluster.x-k8s.io/provider: infrastructure-maas
      data:
        MAAS_API_KEY: >-
          {{ printf "{{ .api_key | toString }}" }}
        MAAS_ENDPOINT: >-
          {{ printf "{{ .endpoint | toString }}" }}
  data:
    - secretKey: api_key
      remoteRef:
        key: maas-api-key
    - secretKey: endpoint
      remoteRef:
        key: maas-endpoint
