---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "dependency-track-ingress"
  namespace: "ci"
  annotations:
  labels:
    app: dependency-track-ingress
spec:
  rules:
    - host: composition-analysis.polarpoint.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: "dependency-track-frontend"
              servicePort: 80