apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlantis-ingress-alt
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: atlantis-non-prod
            port:
              number: 80
    host: polarpoint-io.bainss.eu1.kubegateway.com
  tls:
  - hosts:
    - polarpoint-io.bainss.eu1.kubegateway.com