apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workflows-ingress
  namespace: workflows
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
    
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: argo-workflows-non-prod-server
            port:
              number: 2746
    host: workflows.polarpoint.io
  tls:
  - hosts:
    - workflows.polarpoint.io
    secretName: nginx-ssl-workflows
