---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcp-account-creds
  namespace: iac
spec:
  refreshInterval: 24h0m0s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets-store               # name of the SecretStore (or kind specified)
  target:
    name: gcp-account-creds
    creationPolicy: Owner
    template:
      data:
        credentials: >-
          {{ printf "{{ .gcp_creds | toString }}" }}
  data:
    - secretKey: gcp_creds
      remoteRef:
        key: gcp-creds