apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    initialClusterVersion: "1.23"
    location: us-west2
    networkConfig:
      enableIntraNodeVisibility: true
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    addonsConfig:
      gcePersistentDiskCsiDriverConfig:
        enabled: true
    network: "default"
  writeConnectionSecretToRef:
    namespace: default
    name: gke-conn
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: crossplane-np
spec:
  forProvider:
    autoscaling:
      enabled: true
      maxNodeCount: 5
      minNodeCount: 1
    clusterRef:
      name: example-cluster
    config:
      machineType: n1-standard-1
      diskSizeGb: 120
      diskType: pd-ssd
      imageType: cos_containerd
      labels:
        test-label: crossplane-created
    initialNodeCount: 3
    locations:
      - "us-west2-a"