---
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-terraform
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
  - filename: gcp-credentials.json
    source: Secret
    secretRef:
      namespace: iac
      name: gcp-account-creds
      key: credentials
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      provider "google" {
        credentials = "gcp-credentials.json"
        project     = "polarpoint-demo"
      }

      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-provider-config-terraform"
          namespace         = "iac"
          in_cluster_config = true
        }
      }